### ISSUE TITLE
Error : Module not found "google-search-results-nodejs"

### ISSUE THREAD

**Issue by george19871205** [serpapi/google-search-results-nodejs#3] opened 2020-09-17 18:27 UTC
Hi there
I have installed npm module google-search-results-nodejs and I can see the installed module from node_modules folder.
But it returns this error...

I have tried to change the node.js version. 
Didn't work at all...

Thanks in advance.

![image](https://user-images.githubusercontent.com/60402458/93512144-c901e800-f91b-11ea-88f0-e32dcc8e95d3.png)

**Comment by parker-edwards** [comment] 2020-09-20 08:22
@george19871205 - I experienced this as well. I was able to use the last release, `1.3.0`, to get things working. Assuming you aren't trying to take advantage of any of the `2.0.0` functionality, this may be a suitable workaround

**Comment by GuittonCandice** [comment] 2020-09-21 21:20
@george19871205 I had the same error and it works for me when I require like this 
`const SerpApi = require('google-search-results-nodejs/lib/GoogleSearch');`

**Comment by rrttalv** [comment] 2020-09-28 06:16
I am having the same issue. Downgrading to version `1.3.0` seemed to fix the issue for me too.

**Comment by elizost** [comment] 2020-10-02 21:28
Hello all!

Apologies for the delay in response. I just documented the issue internally and flagged it as urgent. 

I also created a thread on our forum for this here: https://forum.serpapi.com/bugs/p/nodejs-library-error-cannot-find-module-google-search-results-nodejs. You can receive and automatic update when the bug is fixed by adding yourself as a voter on the thread. 

In the future, the quickest way to reach us is by reporting the issue on the forum or emailing us at contact_at_serpapi.com.

Thanks to all for reporting the issue and we'll get everything sorted out for y'all ASAP.

**Comment by jvmvik** [comment] 2020-10-29 02:41
Sorry for the delay in fixing this. 
This is now resolved and released as 2.0.1
https://www.npmjs.com/package/google-search-results-nodejs

The dependency management has been fully revisited and modernized to match modern NodeJS platform.
The regression test are now including a fully Out Of Box Testing where the package is tested again a simple example to verify the overall dependency works.
https://github.com/serpapi/google-search-results-nodejs/actions/runs/334951017

**Closed by jvmvik** 2020-10-29 02:41 UTC
